### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by andreabonadei** [fbiego/retweet#1]
I'd like to request the addition of internationalization to the app for supporting different languages.
I'm not that familiar with Kotlin but I can offer support with this.
I just need some direction on which library to use for this.

I've reached you out on X if you want to chat about this.

**Comment by fbiego** [comment]
Could you provide info on what languages you would like to be added to the application

**Comment by andreabonadei** [comment]
Hello, thanks for your reply!
As of right now I'd like Italian, german and french to be added but once i18n is setup adding new ones should be easy enough.

**Comment by fbiego** [comment]
languages have been added https://github.com/fbiego/retweet/commit/3b7e4d4c4b379d22209840ccb849b863fbbaefa8

**Comment by andreabonadei** [comment]
Thanks a lot for this!
I will create a PR for the Italian translation to improve it a bit!
By testing It I see the drop down to select the languages but It seems not to take effect.
If I change language it still uses the default android language and does not update It.
Can you take a look at It?
Thanks!
