### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by andreabonadei** [fbiego/retweet#2]
The app stopped working.
My X account got limited to the repost limit becausw I respoted to many tweets in a day.
After that the app seems to not be working properly.
Right now It seems the limit has been lifted since I can retweet anything I want without any problem via the X app.
I've already tried the following:
- reinstalling the retweet app without removing data
- reinstalling the X app
- removing the retweet app data and going thourgh the notification setup again

Right now everything is setup correctly but the app Is still not retweeting anything.
Do you have any idea of what I should try next?

Thanks

**Comment by fbiego** [comment]
X (Twitter) removed the repost/retweet action from the notifications, so it is no longer possible
